"""creating table

Revision ID: 324df7b95001
Revises: 
Create Date: 2021-07-09 15:54:21.903521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '324df7b95001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puppy_api',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('puppy_api')
    # ### end Alembic commands ###
